name: GISEle_V1.1
channels:
  - gurobi
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - pandas
  - geopandas
  - rasterio
  - scipy
  - scikit-learn
  - shapely
  - gdal
  - fiona
  - pyproj
  - rtree
  - jupyter
  - ipykernel
  - pyomo
  - gurobi